version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Check for reserved branch names
          command: |
            if [[ $CIRCLE_BRANCH = latest || $CIRCLE_BRANCH = packer || $CIRCLE_BRANCH = tf13 || $CIRCLE_BRANCH = rotator || $CIRCLE_BRANCH = nuker]]; then
              echo "Don't use a branch named 'latest', 'packer', 'tf13', 'rotator' or 'nuker'; these are meaningful tags."
              exit 1
            fi
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build containers
          command: ./build

      - run:
          name: Test containers
          command: ./test

      - run:
          name: Release container
          command: ./release
