version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Check for reserved branch names
          command: |
            if [[ $CIRCLE_BRANCH = latest || $CIRCLE_BRANCH = packer || $CIRCLE_BRANCH = tf12 ]]; then
              echo "Don't use a branch named 'latest' or 'packer'; these are meaningful tags."
              exit 1
            fi
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build containers
          command: ./build

      - run:
          name: Test containers
          command: ./test

      - run:
          name: Release container
          command: |
            for tag in $CIRCLE_SHA1 ${CIRCLE_BRANCH//+([^A-Za-z0-9-.])/-}; 
              
              # latest
              docker tag  trussworks/circleci-docker-primary trussworks/circleci-docker-primary:$tag
              docker push trussworks/circleci-docker-primary:$tag

              # packer
              docker tag  trussworks/circleci-docker-primary:packer trussworks/circleci-docker-primary:packer-$tag
              docker push trussworks/circleci-docker-primary:packer-$tag

              # tf12
              docker tag  trussworks/circleci-docker-primary:tf12 trussworks/circleci-docker-primary:tf12-$tag
              docker push trussworks/circleci-docker-primary:tf12-$tag
            done

            # default tags
            if [[ $CIRCLE_BRANCH = master ]]; then
              docker push trussworks/circleci-docker-primary
              docker push trussworks/circleci-docker-primary:packer
            fi
