version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Check for reserved branch names
          command: ./scripts/check-branch
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build containers
          command: ./scripts/build

      - run:
          name: Test containers
          command: ./scripts/test

      - run:
          name: Release container
          command: ./scripts/release
